spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    dtrver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10086
